"""自己关注自己

Revision ID: a39cf8529e93
Revises: c05b95afe31b
Create Date: 2018-03-02 22:17:05.909444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a39cf8529e93'
down_revision = 'c05b95afe31b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('follow_self', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'follow_self')
    # ### end Alembic commands ###
